# Generated by Django 3.2.7 on 2021-09-13 18:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grocery',
            old_name='Category',
            new_name='category',
        ),
        migrations.AddField(
            model_name='book',
            name='imageurl',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
